root: true
ignorePatterns:
  - '**/*'
  - '!*'
plugins:
  - '@nrwl/nx'
  - eslint-plugin-yml
overrides:
  - files:
      - '*.js'
      - '*.jsx'
      - '*.ts'
      - '*.tsx'
    rules:
      '@nrwl/nx/enforce-module-boundaries':
        - error
        - enforceBuildableLibDependency: true
          allow: []
          depConstraints:
            - sourceTag: '*'
              onlyDependOnLibsWithTags:
                - '*'
      accessor-pairs: error
      arrow-body-style: warn
      class-methods-use-this: error
      curly: warn
      default-case: error
      default-case-last: error
      eqeqeq: warn
      func-style:
        - error
        - declaration
        - allowArrowFunctions: true

      id-length: error
      multiline-comment-style: warn
      new-cap:
        - error
        - capIsNew: false

      no-array-constructor: error
      no-await-in-loop: error
      no-bitwise: error
      no-caller: error
      no-case-declarations: error
      no-confusing-arrow: warn
      no-constant-binary-expression: error
      no-constructor-return: error
      no-delete-var: error
      no-else-return: warn
      no-empty:
        - error
        - allowEmptyCatch: true

      no-empty-function: error
      no-eval: error
      no-extend-native: error
      no-extra-bind: warn
      no-extra-boolean-cast: warn
      no-extra-label: warn
      no-floating-decimal: warn
      no-global-assign: error
      no-implicit-coercion: warn
      no-implicit-globals: error
      no-implied-eval: error
      no-invalid-this: error
      no-iterator: error
      no-label-var: error
      no-lone-blocks: error
      no-lonely-if: warn
      no-mixed-operators: error
      no-multi-assign: error
      no-multi-str: error
      no-negated-condition: error
      no-nested-ternary: error
      no-new: error
      no-new-func: error
      no-new-object: error
      no-new-wrappers: error
      no-nonoctal-decimal-escape: error
      no-octal: error
      no-octal-escape: error
      no-param-reassign: error
      no-promise-executor-return: error
      no-proto: error
      no-redeclare: error
      no-regex-spaces: warn
      no-restricted-properties:
        - error
        - object: Object
          property: assign

      no-restricted-syntax:
        - error

        # const foo = () => {}
        - selector: VariableDeclarator > ArrowFunctionExpression
          message: Arrow function declarations aren't allowed.

        # let foo
        # foo = () => {}
        - selector: AssignmentExpression > ArrowFunctionExpression
          message: Arrow function expressions cannot be assigned to variables.

        # let foo
        # foo = function foo() {}
        - selector: AssignmentExpression > FunctionExpression
          message: Function expressions cannot be assigned to variables.

        # foo: () => {
        #   let bar
        #
        #   return bar
        # }
        - selector: Property > ArrowFunctionExpression > BlockStatement > :first-child:not(ReturnStatement)
          message: Arrow function expressions with a block statement can only be assigned to a property if they only contain a return statement.

      no-return-assign: error
      no-script-url: error
      no-self-compare: error
      no-sequences: error
      no-shadow-restricted-names: error
      no-template-curly-in-string: error
      no-throw-literal: error
      no-undef-init: warn
      no-undefined: error
      no-underscore-dangle:
        - error
        - allowFunctionParams: true

      no-unneeded-ternary:
        - warn
        - defaultAssignment: false

      no-unreachable-loop: error
      no-unused-expressions: error
      no-unused-private-class-members: error
      no-useless-call: error
      no-useless-catch: error
      no-useless-computed-key: warn
      no-useless-concat: error
      no-useless-constructor: error
      no-useless-escape: error
      no-useless-rename: warn
      no-useless-return: warn
      no-var: warn
      no-void: error
      no-with: error
      object-shorthand: warn
      one-var:
        - warn
        - never

      operator-assignment: warn
      prefer-arrow-callback: warn
      prefer-const: warn
      prefer-destructuring:
        - error
        - object: false
          array: true

      prefer-exponentiation-operator: warn
      prefer-named-capture-group: error
      prefer-numeric-literals: warn
      prefer-object-has-own: warn
      prefer-object-spread: warn
      prefer-promise-reject-errors: error
      prefer-regex-literals:
        - error
        - disallowRedundantWrapping: true

      prefer-rest-params: error
      prefer-spread: error
      prefer-template: warn
      quote-props:
        - warn
        - as-needed

      radix:
        - warn
        - as-needed

      require-atomic-updates: error
      require-await: error
      require-unicode-regexp: error
      require-yield: error
      sort-keys:
        - error
        - asc
        - allowLineSeparatedGroups: true
          natural: true

      spaced-comment: warn
      symbol-description: error
      yoda: warn

  - files:
      - '*.ts'
      - '*.tsx'
    extends:
      - 'plugin:@nrwl/nx/typescript'
    plugins:
      - import
    rules:
      '@typescript-eslint/adjacent-overload-signatures': error
      '@typescript-eslint/array-type':
        - warn
        - default: array

      '@typescript-eslint/await-thenable': error
      '@typescript-eslint/ban-ts-comment':
        - error
        - ts-expect-error:
            descriptionFormat: '^: TS\\d+ .+$'

      '@typescript-eslint/ban-types': warn
      '@typescript-eslint/class-literal-property-style': warn
      '@typescript-eslint/consistent-generic-constructors': error
      '@typescript-eslint/consistent-indexed-object-style': error
      '@typescript-eslint/consistent-type-assertions': error
      '@typescript-eslint/consistent-type-definitions': warn
      '@typescript-eslint/consistent-type-exports': warn
      '@typescript-eslint/consistent-type-imports': warn
      '@typescript-eslint/default-param-last': error
      '@typescript-eslint/explicit-member-accessibility':
        - warn
        - overrides:
            constructors: no-public

      '@typescript-eslint/no-useless-constructor': warn
      '@typescript-eslint/member-ordering': error
      '@typescript-eslint/method-signature-style': warn
      '@typescript-eslint/naming-convention':
        - error
        - selector: default
          format:
            - camelCase

          leadingUnderscore: forbid
          trailingUnderscore: forbid

        - selector: enumMember
          format:
            - StrictPascalCase

        - selector: parameter
          format:
            - camelCase

          leadingUnderscore: allow

        - selector: typeLike
          format:
            - StrictPascalCase

        - selector: typeParameter
          format:
            - StrictPascalCase

          prefix:
            - T

        - selector: variable
          modifiers:
            - exported

          format:
            - camelCase

        - selector: variable
          modifiers:
            - const
            - global

          format:
            - UPPER_CASE

        - selector: variable
          modifiers:
            - const
            - exported
            - global

          format:
            - camelCase
            - UPPER_CASE

      '@typescript-eslint/no-array-constructor': warn
      '@typescript-eslint/no-base-to-string': error
      '@typescript-eslint/no-confusing-non-null-assertion': warn
      '@typescript-eslint/no-confusing-void-expression': warn
      '@typescript-eslint/no-dupe-class-members': error
      '@typescript-eslint/no-duplicate-enum-values': error
      '@typescript-eslint/no-dynamic-delete': warn
      '@typescript-eslint/no-empty-interface': warn
      '@typescript-eslint/no-explicit-any':
        - warn
        - fixToUnknown: true

      '@typescript-eslint/no-extra-non-null-assertion': warn
      '@typescript-eslint/no-extraneous-class': error
      '@typescript-eslint/no-floating-promises': error
      '@typescript-eslint/no-implied-eval': error
      '@typescript-eslint/no-inferrable-types': warn
      '@typescript-eslint/no-invalid-this': error
      '@typescript-eslint/no-loop-func': error
      '@typescript-eslint/no-loss-of-precision': error
      '@typescript-eslint/no-magic-numbers':
        - error
        - ignoreArrayIndexes: true
          ignoreEnums: true
          ignoreNumericLiteralTypes: true
          ignoreReadonlyClassProperties: true
          ignoreTypeIndexes: true

      '@typescript-eslint/no-meaningless-void-operator':
        - warn
        - checkNever: true

      '@typescript-eslint/no-misused-new': error
      '@typescript-eslint/no-misused-promises': error
      '@typescript-eslint/no-namespace': error
      '@typescript-eslint/no-non-null-asserted-nullish-coalescing': error
      '@typescript-eslint/no-non-null-asserted-optional-chain': error
      '@typescript-eslint/no-non-null-assertion': error
      import/no-duplicates: error
      no-useless-constructor: off

  - files:
      - '*.js'
      - '*.jsx'
    extends:
      - 'plugin:@nrwl/nx/javascript'
    rules:
      camelcase: error
      dot-notation: warn
      no-duplicate-imports: error
      no-loop-func: error
      no-loss-of-precision: error
      no-magic-numbers:
        - error
        - ignoreArrayIndexes: true

  - files:
      - '*.js'
      - '*.jsx'
      - '*.tsx'
    rules:
      no-alert: error

  - files:
      - '*.yaml'
      - '*.yml'
    extends:
      - plugin:yml/recommended
      - plugin:yml/prettier
    rules:
      yml/plain-scalar: error
