root: true
ignorePatterns:
  - '**/*'
  - '!*'
plugins:
  - '@nrwl/nx'
  - eslint-plugin-yml
overrides:
  - files:
      - '*.js'
      - '*.jsx'
      - '*.ts'
      - '*.tsx'
    rules:
      '@nrwl/nx/enforce-module-boundaries':
        - error
        - enforceBuildableLibDependency: true
          allow: []
          depConstraints:
            - sourceTag: '*'
              onlyDependOnLibsWithTags:
                - '*'
      no-await-in-loop: error
      no-constant-binary-expression: warn
      no-constructor-return: warn
      no-duplicate-imports: error

  - files:
      - '*.ts'
      - '*.tsx'
    extends:
      - 'plugin:@nrwl/nx/typescript'
    rules: {}

  - files:
      - '*.js'
      - '*.jsx'
    extends:
      - 'plugin:@nrwl/nx/javascript'
    rules: {}

  - files:
      - '*.yaml'
      - '*.yml'
    extends:
      - plugin:yml/recommended
      - plugin:yml/prettier
    rules:
      yml/plain-scalar: error
