root: true
ignorePatterns:
  - '**/*'
  - '!*'
plugins:
  - '@nrwl/nx'
  - eslint-plugin-yml
overrides:
  - files:
      - '*.js'
      - '*.jsx'
      - '*.ts'
      - '*.tsx'
    rules:
      '@nrwl/nx/enforce-module-boundaries':
        - error
        - enforceBuildableLibDependency: true
          allow: []
          depConstraints:
            - sourceTag: '*'
              onlyDependOnLibsWithTags:
                - '*'
      accessor-pairs: error
      arrow-body-style: warn
      camelcase: error
      class-methods-use-this: error
      curly: warn
      default-case: error
      default-case-last: error
      eqeqeq: warn
      func-style:
        - error
        - declaration
        - allowArrowFunctions: true

      id-length: error
      multiline-comment-style: warn
      new-cap:
        - error
        - capIsNew: false

      no-array-constructor: error
      no-await-in-loop: error
      no-bitwise: error
      no-caller: error
      no-case-declarations: error
      no-confusing-arrow: warn
      no-constant-binary-expression: error
      no-constructor-return: error
      no-delete-var: error
      no-duplicate-imports: error
      no-else-return: warn
      no-empty:
        - error
        - allowEmptyCatch: true

      no-empty-function: error
      no-eval: error
      no-extend-native: error
      no-extra-bind: warn
      no-extra-boolean-cast: warn
      no-extra-label: warn
      no-extra-semi: warn
      no-floating-decimal: warn
      no-global-assign: error
      no-implicit-coercion: warn
      no-implicit-globals: error
      no-implied-eval: error
      no-invalid-this: error
      no-iterator: error
      no-label-var: error
      no-lone-blocks: error
      no-lonely-if: warn
      no-loop-func: error
      no-magic-numbers:
        - error
        - ignoreArrayIndexes: true

      no-mixed-operators: error
      no-multi-assign: error
      no-multi-str: error
      no-negated-condition: error
      no-nested-ternary: error
      no-new: error
      no-new-func: error
      no-new-object: error
      no-new-wrappers: error
      no-nonoctal-decimal-escape: error
      no-octal: error
      no-octal-escape: error
      no-param-reassign: error
      no-promise-executor-return: error
      no-proto: error
      no-redeclare: error
      no-regex-spaces: warn
      no-restricted-properties:
        - error
        - object: Object
          property: assign

      no-restricted-syntax:
        - error
        - VariableDeclarator[init.type='ArrowFunctionExpression']
        - VariableDeclarator[init.type='FunctionExpression']

      no-return-assign: error
      no-script-url: error
      no-self-compare: error
      no-sequences: error
      no-shadow-restricted-names: error
      no-template-curly-in-string: error
      no-throw-literal: error
      no-undef-init: warn
      no-undefined: error
      no-underscore-dangle:
        - error
        - allowFunctionParams: true

      no-unneeded-ternary:
        - warn
        - defaultAssignment: false

      no-unreachable-loop: error
      no-unused-expressions: error
      no-unused-private-class-members: error
      no-useless-call: error
      no-useless-catch: error
      no-useless-computed-key: warn
      require-atomic-updates: error

  - files:
      - '*.ts'
      - '*.tsx'
    extends:
      - 'plugin:@nrwl/nx/typescript'

  - files:
      - '*.js'
      - '*.jsx'
    extends:
      - 'plugin:@nrwl/nx/javascript'
    rules:
      dot-notation: warn

  - files:
      - '*.js'
      - '*.jsx'
      - '*.tsx'
    rules:
      no-alert: error

  - files:
      - '*.yaml'
      - '*.yml'
    extends:
      - plugin:yml/recommended
      - plugin:yml/prettier
    rules:
      yml/plain-scalar: error
