---
root: true
extends:
  - plugin:yml/recommended
ignorePatterns:
  - '**/*'
  - '!*'
plugins:
  - '@nrwl/nx'
  - eslint-plugin-yml
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
      - '*.js'
      - '*.jsx'
    rules:
      '@nrwl/nx/enforce-module-boundaries':
        - error
        - enforceBuildableLibDependency: true
          allow: []
          depConstraints:
            - sourceTag: '*'
              onlyDependOnLibsWithTags:
                - '*'
  - files:
      - '*.ts'
      - '*.tsx'
    extends:
      - 'plugin:@nrwl/nx/typescript'
    rules: {}
  - files:
      - '*.js'
      - '*.jsx'
    extends:
      - 'plugin:@nrwl/nx/javascript'
    rules: {}
  - files:
      - '*.yml'
      - '*.yaml'
    rules:
      yml/plain-scalar:
        - error
        - always
