root: true
ignorePatterns:
  - '**/*'
  - '!*'
plugins:
  - '@nrwl/nx'
  - eslint-plugin-yml
overrides:
  - files:
      - '*.js'
      - '*.jsx'
      - '*.ts'
      - '*.tsx'
    rules:
      '@nrwl/nx/enforce-module-boundaries':
        - error
        - enforceBuildableLibDependency: true
          allow: []
          depConstraints:
            - sourceTag: '*'
              onlyDependOnLibsWithTags:
                - '*'
      accessor-pairs: error
      arrow-body-style: warn
      camelcase: error
      class-methods-use-this: error
      curly: warn
      default-case: error
      default-case-last: error
      eqeqeq: warn
      func-style:
        - error
        - declaration
        - allowArrowFunctions: true

      id-length: error
      no-await-in-loop: error
      no-constant-binary-expression: error
      no-constructor-return: error
      no-duplicate-imports: error
      no-promise-executor-return: error
      no-self-compare: error
      no-template-curly-in-string: error
      no-unreachable-loop: error
      no-unused-private-class-members: error
      require-atomic-updates: error

  - files:
      - '*.ts'
      - '*.tsx'
    extends:
      - 'plugin:@nrwl/nx/typescript'

  - files:
      - '*.js'
      - '*.jsx'
    extends:
      - 'plugin:@nrwl/nx/javascript'
    rules:
      dot-notation: warn

  - files:
      - '*.yaml'
      - '*.yml'
    extends:
      - plugin:yml/recommended
      - plugin:yml/prettier
    rules:
      yml/plain-scalar: error
