'*.!({js,jsx,ts,tsx,yml,yaml})':
  - &prettier prettier --cache --cache-strategy content --write

'*.{js,jsx,ts,tsx,yml,yaml}':
  - eslint --cache --cache-strategy content --fix --max-warnings 0
  - *prettier
