'*.!({js,jsx,ts,tsx,yaml,yml})':
  - &prettier prettier --cache --cache-strategy content --ignore-unknown --write

'*.{js,jsx,ts,tsx,yaml,yml}':
  - eslint --cache --cache-strategy content --fix --max-warnings 0
  - *prettier
