version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14.17.3
    steps:
      - checkout
      - run:
          name: Install PNPM
          command: |
            sudo npm install --global pnpm@6.3.0
      - run:
          name: Install Global Packages
          command: |
            sudo pnpm add --global @microsoft/rush@5.47.0
      - run:
          name: Install scripts packages
          working_directory: ./scripts
          command: |
            pnpm install
      - run:
          name: Combine packages' package.json
          command: |
            node scripts/src/combine-packages.js > combined-packages.txt
      - restore_cache:
          keys:
            - v2-deps-{{ checksum "combined-packages.txt" }}
            - v2-deps-
      - run:
          name: Install Dependencies
          command: |
            rush update
      - save_cache:
          key: v2-deps-{{ checksum "combined-packages.txt" }}-3
          paths:
            - /home/circleci/.pnpm-store/v3
            - ./common/temp
      - run:
          name: Lint packages
          command: |
            rush lint
      - run:
          name: Combine project's build caches
          command: |
            node scripts/src/combine-build-caches.js > combined-build-caches.txt
      - restore_cache:
          keys:
            - v2-build-{{ checksum "combined-build-caches.txt" }}-{{ checksum "combined-packages.txt" }}
            - v2-build-{{ checksum "combined-build-caches.txt" }}
            - v2-build-
      - run:
          name: Build
          command: |
            rush build
      - save_cache:
          key: v2-build-{{ checksum "combined-build-caches.txt" }}-{{ checksum "combined-packages.txt" }}
          paths:
            - ./packages/decision-tables/.rush/temp/package-deps_build.json
            - ./packages/decision-tables/dist/
            - ./packages/pivotal-story-branch/.rush/temp/package-deps_build.json
            - ./packages/pivotal-story-branch/dist/
      - run:
          name: Run tests
          command: |
            rush test
  release:
    docker:
      - image: circleci/node:14.17.3
    steps:
      - checkout
      - run:
          name: Install PNPM
          command: |
            sudo npm install --global pnpm@6.3.0
      - run:
          name: Install Global Packages
          command: |
            sudo pnpm add --global @microsoft/rush@5.47.0
      - run:
          name: Install scripts packages
          working_directory: ./scripts
          command: |
            pnpm install
      - run:
          name: Combine packages' package.json
          command: |
            node scripts/src/combine-packages.js > combined-packages.txt
      - restore_cache:
          keys:
            - v2-deps-{{ checksum "combined-packages.txt" }}
            - v2-deps-
      - run:
          name: Link Dependencies
          command: |
            rush link
      - run:
          name: Combine project's build caches
          command: |
            node scripts/src/combine-build-caches.js > combined-build-caches.txt
      - restore_cache:
          keys:
            - v2-build-{{ checksum "combined-build-caches.txt" }}-{{ checksum "combined-packages.txt" }}
            - v2-build-{{ checksum "combined-build-caches.txt" }}
            - v2-build-
      - run:
          name: build
          command: |
            rush build
      - run:
          name: release
          command: |
            rush release

workflows:
  test-and-release:
    jobs:
      - test
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - release:
          requires:
            - hold
          context:
            - npm-auth
            - utils
