version: 2.1

jobs:
  test-and-build:
    docker:
      - image: circleci/node:14.17.3
    steps:
      - checkout
      - run:
          name: Install PNPM
          command: |
            sudo npm install --global pnpm
      - run:
          name: Install Global Packages
          command: |
            sudo pnpm add --global @microsoft/rush
      - run:
          name: Install scripts packages
          working_directory: ./scripts
          command: |
            pnpm install
      - run:
          name: Combine projects' package.json
          command: |
            node scripts/src/combine-projects-packages.js > combined-projects-packages.txt
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "combined-projects-packages.txt" }}
            - v1-deps-
      - run:
          name: Install Dependencies
          command: |
            rush update
      - save_cache:
          key: v1-deps-{{ checksum "combined-projects-packages.txt" }}
          paths:
            - /home/circleci/.pnpm-store/v3
      - run:
          name: Combine project's build caches
          command: |
            node scripts/src/combine-build-caches.js > combined-build-caches.txt
      - restore_cache:
          keys:
            - v1-build-{{ checksum "combined-build-caches.txt" }}-{{ checksum "combined-projects-packages.txt" }}
            - v1-build-{{ checksum "combined-build-caches.txt" }}
            - v1-build-
      - run:
          name: Build
          command: |
            rush build
      - save_cache:
          key: v1-build-{{ checksum "combined-build-caches.txt" }}-{{ checksum "combined-projects-packages.txt" }}
          paths:
            - ./projects/decision-table/.rush/temp/package-deps_build.json
      - run:
          name: Run tests
          command: |
            rush test
  release:
    docker:
      - image: circleci/node:14.17.3
    steps:
      - checkout
      - run:
          name: Install PNPM
          command: |
            sudo npm install --global pnpm
      - run:
          name: Install Global Packages
          command: |
            sudo pnpm add --global @microsoft/rush
      - run:
          name: Install scripts packages
          working_directory: ./scripts
          command: |
            pnpm install
      - run:
          name: Combine projects' package.json
          command: |
            node scripts/src/combine-projects-packages.js > combined-projects-packages.txt
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "combined-projects-packages.txt" }}
            - v1-deps-
      - run:
          name: Install Dependencies
          command: |
            rush update
      - run:
          name: Combine project's build caches
          command: |
            node scripts/src/combine-build-caches.js > combined-build-caches.txt
      - restore_cache:
          keys:
            - v1-build-{{ checksum "combined-build-caches.txt" }}-{{ checksum "combined-projects-packages.txt" }}
            - v1-build-{{ checksum "combined-build-caches.txt" }}
            - v1-build-
      - run:
          name: build
          command: |
            rush build
      - run:
          name: release
          command: |
            rush semantic-release

workflows:
  test-and-release:
    jobs:
      - test-and-build
      - release:
          filters:
            branches:
              only: master
          requires:
            - test-and-build
          context:
            - npm-auth
